
version: "3.8"

networks:
  traefik_net:
  prometheus_net:

services:

  loki:
    image: docker.io/grafana/loki:3.3.1
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - traefik_net
      - prometheus_net
    volumes:
      - /data/configs/loki/loki.yml:/etc/loki/local-config.yaml:ro
      - /data/loki:/loki
    deploy:
      replicas: 1
      labels:
        - prometheus.io/scrape-me=yes-please
        - prometheus.io/metrics-path=/metrics
        - prometheus.io/metrics-port=3100

  promtail:
    image: docker.io/grafana/promtail:3.2.2
    command: -config.file=/etc/promtail/config.yml
    networks:
      - traefik_net
      - prometheus_net
    volumes:
      - /data/configs/promtail/promtail.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      labels:
        - prometheus.io/scrape-me=yes-please
        - prometheus.io/metrics-path=/metrics
        - prometheus.io/metrics-port=9080

  prometheus:
    image: quay.io/prometheus/prometheus:v3.0.1
    user: root
    command:
      - --web.listen-address=0.0.0.0:9090
      - --web.external-url=http://prometheus.vcc.internal
      - --storage.tsdb.retention.time=14d
    networks:
      - traefik_net
      - prometheus_net
    volumes:
      - /data/configs/prometheus/prometheus.yml:/prometheus/prometheus.yml:ro
      - /data/prometheus:/prometheus/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=vcc_traefik_net
        - traefik.http.routers.prometheus.rule=Host(`prometheus.vcc.internal`)
        - traefik.http.routers.prometheus.service=prometheus
        - traefik.http.services.prometheus.loadbalancer.server.port=9090

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    hostname: "{% raw %}{{.Node.Hostname}}{% endraw %}"
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
    networks:
      - prometheus_net
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro,rslave
      - /sys:/host/sys:ro,rslave
    deploy:
      endpoint_mode: dnsrr
      mode: global
      labels:
        - prometheus.io/scrape-me=yes-please
        - prometheus.io/metrics-path=/metrics
        - prometheus.io/metrics-port=9100
