
version: "3.8"

networks:
  metrics_net:

services:

  terminal:
    image: public.ecr.aws/docker/library/alpine:3.21
    entrypoint: [ '/bin/sh', '-c' ]
    command: [ 'while true; do sleep 1; done' ]
    networks: [ 'metrics_net' ]
    deploy:
      mode: global

  web:
    image: public.ecr.aws/docker/library/nginx:1.27-alpine
    networks: [ 'metrics_net' ]
    volumes: [ '/etc/hostname:/usr/share/nginx/html/hostname:ro' ]
    deploy:
      endpoint_mode: dnsrr
      replicas: 3
