services:

  traefik:
    networks:
      traefik_net:
        aliases:
          # if we had put this alias on the service it would mean
          #   inside of the cluster we should go to auth.vcc.internal:5556
          #   outside of the cluster we should go to auth.vcc.internal:80
          # instead, here everything is consistent both east-west and north-south!
          - auth.vcc.internal

  dex:
    image: ghcr.io/dexidp/dex:v2.41.1-alpine
    user: root
    networks:
      traefik_net:
    deploy:
      labels:
        - "traefik.enable=true" # hi traefik, I'm your guy
        - "traefik.docker.network=vcc_traefik_net" # where can traefik find this container?
        - "traefik.http.routers.dex.rule=Host(`auth.vcc.internal`)"
        - "traefik.http.routers.dex.service=dex"
        - "traefik.http.services.dex.loadbalancer.server.port=5556"
    volumes:
      - /data/dex:/data
      - /data/configs/dex/dex.yaml:/etc/dex/config.docker.yaml:ro
