
issuer: https://auth.vcc.internal

storage:
  type: sqlite3
  config:
    file: /data/dex.db

web:
  http: 0.0.0.0:5556

oauth2:
  grantTypes:
    - authorization_code
  skipApprovalScreen: true
  passwordConnector: local

staticClients:
  - id: forgejo
    redirectURIs:
      - 'https://git.vcc.internal'
    name: 'Forgejo Git'
    secret: forgejo-secret

  - id: grafana
    redirectURIs:
      - 'https://grafana.vcc.internal/login/generic_oauth'
    name: 'Grafana'
    secret: grafana-secret

enablePasswordDB: true
staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
