server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: docker_containers
    pipeline_stages:
      - docker: {}
    docker_sd_configs: # https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#docker_sd_configs
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # grab the container name
      - source_labels: [ '__meta_docker_container_name' ]
        target_label: container_name
        action: replace
      # grab the existing container labels
      - regex: __meta_docker_container_label_(.+)
        replacement: container_label_$1
        action: labelmap
