---
# configure docker to accept insecure registries
- name: Copy docker daemon.json
  ansible.builtin.template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: Restart docker
- meta: flush_handlers

# add registry.vcc.internal as an alias to localhost in /etc/hosts
- name: Add registry.vcc.internal to /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.+registry.vcc.internal$'
    line: "127.0.0.1 registry.vcc.internal"
